pipeline:
  lint:
    image: debian:stable-slim
    commands:
      - echo test
      - sleep 5
      - echo test1
      - sleep 5
      - echo test2
      - sleep 1m
      - echo end
      - sleep 5
      - echo more checks
      - sleep 10
      - echo tada
  trouble:
    image: debian:stable-slim
    commands:
      - echo trouble
      - sleep 5
      - echo maker
      - sleep 5
      - echo has some
      - sleep 1m
      - echo fun
      - sleep 5
      - echo with colors.
      - sleep 10
      - echo -e "I \033[0;31mlove\033[0m colors"
      - exit -2
