pipeline:
  test:
    image: debian:stable-slim
    commands:
      - env
      - echo test
      - chmod +x ./counter.sh
      - ./counter.sh
    secrets:
      - source: gitea_token
        target: plugin_gitea_token
